### PR TITLE
lotsa stuff

### PR DESCRIPTION
**Pull request by jozsefsallai**
This PR fixes some stuff and adds unit tests. Changes:
 - `===` in favor of `==` everywhere except where `==` is required
 - consistent semicolon (hah) usage
 - removed some unused variables
 - added gitignore
 - added unit tests
 - added "polyfill" keyword (since it's what this actually is)
 - fixed main entry name (arr.js doesn't exist, it's index.js, some environments might have a hard time picking the module up)

I'd also suggest using a linter like eslint!

-- ad finitum 🐱 💡

### CODE REVIEW

**Comment by GDColon** [comment]
This is awesome, thanks!
Mind going into a little bit of detail on what `library.test.js` is? Never seen something like that before 👀

**Comment by LegoDevStudio** [comment]
library.test.js is a testing file to make sure the module works fine before updating. Running `npm test` will execute the test file.

**Comment by jozsefsallai** [comment]
it's the test script! the usual naming convention is `[originalFileName].test.js`, but index.test.js sounds lame so i went with library.

anyway, this file contains definitions for [mocha](https://mochajs.org/) to parse and run the [chai](https://www.chaijs.com/) assertions on. If you run `npm run test` in the console, it will run the tests that are defined in the library.test.js file.

**Comment by GDColon** [comment]
Sounds cool! (i'll try to figure out how it works in case I ever add more methods)
Thanks for contributing <3

**Pull request merged**
